### ISSUE TITLE
Error: error getting endorser client for query

### ISSUE THREAD

**Issue by yuanyh997** [litong01/minifabric#1]
系统 ubuntu18.04
执行 sudo ./minifab generate -c mychannel 时失败，说是没有指定'hostroot'变量，后面在mainfuncs.sh的generateCerts()添加
-e "hostroot=$(pwd)" 后成功运行，安装fabcar链码过程无报错，但是进入cli 执行 peer chaincode query -C mychannel -n mycc -c '{"Args":["initLedger"]}' 命令之后出现 
"Error: error getting endorser client for query: endorser client failed to connect to 0.0.0.0:7051: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 0.0.0.0:7051: connect: connection refused"
"

**Comment by litong01** [comment]
generate is to generate a new set of certs and artifacts. when do generate,
the channel parameter is not used.

if you meant to create a new channel named mychannel, then you should do
this

minifab create -c mychannel
minifab join -c mychannel
minifab install
minifab instantiate -c mychannel

please do that and let me know how it goes.

minifab up at present does not create any application channels, I will add
that today maybe.

Thanks.

Tong Li
IBM Open Technology

**Comment by yuanyh997** [comment]
感谢回复！我按照您说的步骤重新运行并创建了频道mychannel ，之后安装并实例化了chaincode_example02过程中没有报错。但是当我进入cli运行
peer chaincode query -C mychannel -n chaincode_example02 -c '{"Args":["query","a"]}'&nbsp; 时仍然出现上诉错误。在我认为命令没有出错的情况下，我查看docker发现链码容器dev-peer2.org0.example.com-chaincode_example02-1.0已经在运行，而且查看节点日志发现
1. 链码容器输出 ：ex02 Init Aval = 100, Bval = 200（是否说明实例化成功？）
2. orderer3容器其余输出正常但是有输出：2020-01-07 01:45:50.745 UTC [common.deliver] deliverBlocks -&gt; WARN 034 [channel: mychannel] Rejecting deliver request for 172.25.0.9:33510 （cli地址）because of consenter error
3. orderer1容器其余正常有输出：2020-01-07 01:47:54.296 UTC [orderer.common.broadcast] Handle -&gt; WARN 03d Error reading from 172.25.0.9:50942: rpc error: code = Canceled desc = context canceled
4.peer节点输出正常，也已经成块


具体输出在附件，all.log是运行命令行时的输出，docker.log是容器的日志




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"litong01"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月6日(星期一) 晚上10:17
收件人:&nbsp;"litong01/minifabric"<minifabric@noreply.github.com&gt;;
抄送:&nbsp;"袁轶皓"<420883453@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [litong01/minifabric] Error: error getting endorser client for query (#1)



generate is to generate a new set of certs and artifacts. when do generate, 
 the channel parameter is not used. 
 
 if you meant to create a new channel named mychannel, then you should do 
 this 
 
 minifab create -c mychannel 
 minifab join -c mychannel 
 minifab install 
 minifab instantiate -c mychannel 
 
 please do that and let me know how it goes. 
 
 minifab up at present does not create any application channels, I will add 
 that today maybe. 
 
 Thanks. 
 
 Tong Li 
 IBM Open Technology

**Comment by litong01** [comment]
default channel name is called firstchannel, not mychannel, I probably
should set the default channel to be mychannel. Let me work on that.

Thanks.

Tong Li
IBM Open Technology

**Comment by litong01** [comment]
I have changed the default channel name to be "mychannel", you can pull the
latest image "docker pull hfrd/minifab:latest" and try again.
Alternatively you can do the following:

minifab create -c mychannel
minifab join -c mychannel
minifab instantiate -c mychannel

assume that you have already installed some chaincode, then you should be
ok.

Thanks.

Tong Li
IBM Open Technology

**Comment by litong01** [comment]
What error did you see? I tried the exact same query and I got the correct value. Can you make sure before you do the command, you should set up all environment variables such as which peer, tls cert etc.

**Comment by litong01** [comment]
I've also made a lot of changes to support 2.0, please pull the new image. Now the default channel is called mychannel and the default chaincode is called `simple`, you can try these with the latest image. If you see no errors, please close this. If you still see errors, please copy your errors here.

**Comment by litong01** [comment]
I've also tried the same thing on 2.0 and everything worked as expected. see this results:

peer chaincode query -C mychannel -n simple -c '{"Args":["query","a"]}'
200

When you see chaincode containers up running, that means your chaincode actually was installed and instantiated (committed) successfully.

**Comment by litong01** [comment]
this is an user error. and minifab behaves as it should.
