### ISSUE TITLE
Error: got unexpected status: SERVICE_UNAVAILABLE -- no Raft leader

### ISSUE THREAD

**Issue by kimisan** [litong01/minifabric#12]
after run sudo ./minifab up, I found this error
OS: ubuntu-20.04-desktop-amd64
Docker, 
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.13.4

# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  download images
............
# Running operation: ******************************************
  generate certificates
.............
# Running operation: ******************************************
  start network
....................
# Running operation: ******************************************
  channel create

.....
# Run the channel creation script on cli container ************
  non-zero return code
  2020-05-16 09:08:00.320 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
  2020-05-16 09:08:00.346 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /vars/configtx.yaml
  2020-05-16 09:08:00.346 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 003 Generating new channel configtx
  2020-05-16 09:08:00.348 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 004 Writing new channel tx
  2020-05-16 09:08:00.393 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
  Error: got unexpected status: SERVICE_UNAVAILABLE -- no Raft leader

# STATS *******************************************************
minifab: ok=92	failed=1

**Comment by litong01** [comment]
@kimisan this is due to the fact that when try to performance the channel operation, the orderers may not have finished communicating with each other. Please wait few seconds to try the following command to see if it runs ok.

```minifab create```

**Comment by kimisan** [comment]
@litong01 cool, it is ok now.

**Comment by litong01** [comment]
@kimisan if it is all possible, do this to test.

```minifab netup
minifab create
```

**Comment by litong01** [comment]
@kimisan in that case, can you close this issue?

**Comment by litong01** [comment]
@kimisan I've also added quite few new features to enable node health and metrics, and improved `minifab stats` function. Check it out by simply updating the hfrd/minifab:latest image.

**Comment by edkaz** [comment]
I too had this issue, waited around 15-20 seconds and then ran _minifab create_.  It looks like it worked just fine or at least I did not get any `failed` status.
