### ISSUE TITLE
Minfab Initialisation Failures

### ISSUE THREAD

**Issue by edkaz** [litong01/minifabric#18]
Hello,
I'm new to minifab and to Hyperledger 2.X and I'm trying to build a smallnetwork (7 nodes) and install my own chaincode - called _scaffold_ on it. I've performed the following steps successfully:
1. Created the specification of the network and executed ```minifab up```
2. ```minifab install -n scaffold -l node```
3. ```minifab approve```
4. ```minifab commit ```
5. ```minifab discover```

I then execute
```[bash]
minifab invoke -p '"CreateAsset","{hello:world}","a,b","c,d"'
```
But I get:
```[bash]
non-zero return code
  Error: endorsement failure during invoke. response: status:500 message:"error in simulation: failed to execute transaction bba341430d5da9523848a6238bf17bc02660f24838763dfdbb5362eb4ab64490: invalid invocation: chaincode 'scaffold' has not been initialized for this version, must call as init first"
```
I've missed something but I can't see what it is that I've missed. The context looks as follows:
```[bash]
Minifab Execution Context:
    FABRIC_RELEASE=2.1
    CHANNEL_NAME=jv
    PEER_DATABASE_TYPE=couchdb
    CHAINCODE_LANGUAGE=node
    CHAINCODE_NAME=scaffold
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="CreateAsset","{hello:world}","a,b","c,d"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=pnt.jv.com
    HOST_ADDRESSES=10.0.0.29
    WORKING_DIRECTORY: .../Hyperledger/Hyperledger-2.1/fabric-prototype-v2
```
Help greatly appreciated. Thanks - Ed

**Comment by aguel** [comment]
can you post the error message and details? I think your posting got cut off.

**Comment by edkaz** [comment]
Thank you. That worked. 
Perhaps add this step to your documentation when you get a chance. 
Warmest regards - Ed
