### ISSUE TITLE
Chaincode Methods

### ISSUE THREAD

**Issue by neutralsecond** [litong01/minifabric#2]
How to invoke chaincode methods?

**Comment by litong01** [comment]
minifab invoke -p '"methodname","p1","p2","'3",...' etc.

notice that the entire parameters need to be in single quote, and each
parameter need to be in double quote and separated by comma.

For example, if you are using the simple chaincode, here are two examples

minifab invoke -p '"invoke","a","b","4"'

minifab invoke -p '"query","a"'

The first example invoke the invoke method, and the second example invoke
the query method.

Last couple of days, I have made a lot of improvement to minifab, you
probably can pull the latest minifab image again and take advantages of new
functions. I have also updated the readme doc to reflect what I wrote
above.

Tong Li
IBM Open Technology

**Comment by litong01** [comment]
Please see the README.md file just updated. If that doc is sufficient, please close this.

**Comment by neutralsecond** [comment]
I get this error message for any operation.

`
sudo ./minifab.sh dashup

Current parameters used in the process:
CHANNEL_NAME=mychannel
DB_TYPE=golevel
BLOCK_NUMBER=
IMAGETAG=1.4.4
CC_LANGUAGE=go
CC_VERSION=1.0
CC_NAME=simple
CC_PARAMETERS="query","a"
EXPOSE_ENDPOINTS=
HOSTADDRS=
HOSTROOTDIR: /home/ahmet/Desktop/minifabric
scripts/mainfuncs.sh: line 150: ansible-playbook: command not found
`

**Comment by litong01** [comment]
Looks like you did not download the right script. When you do the following,

curl -o minifab -L https://tinyurl.com/twrt8zv && chmod +x minifab

It downloads the minifab script, not the minifab.sh which are different files. minifab.sh should never be on your host machine. it is packaged in the minifab container.

**Comment by litong01** [comment]
This is a user error and provided answer and no response. closing this.
