### ISSUE TITLE
Creating a channel from another machine in multiple machine configuration  channelupdate ERROR

### ISSUE THREAD

**Issue by Tsine** [litong01/minifabric#22]
I trying to setup a multiple machine netowrk with VMs. I have VM1 and VM2 with spec.yaml attached in bellow 
So the sequence of commands are 
```
VM1:
project#./minifab up -e true
project#./minifab profilegen
project# scp vars/profiles/endpoints.yaml user@192.168.0.111:/home/user/go/src/github.com/hyperledger/project/vars
project# docker exec cli /vars/run/fetchsystemchannel.sh
```
####
for some reason` project#./minifab channelquery -c systemchannel` returns an empty json
That's why I

 run my own script (you can find it attached).
Feel free to suggest me a more efficient way to update systemchannel consortium
####
```
VM2:
project#./minifab netup -e true -o org2.example.com
project#./minifab nodeimport
```
 ####
```
VM1:
project#nano ./vars/systemchannel_config.json
```
Now I add in the consortium the org2 (JoinRequest_org2examplecom.json) changing the systemchannel_config
```
 "Consortiums": {
        "groups": {
          "SampleConsortium": {
            "groups": {
              "org0examplecom": {},
               "org1examplecom": {},
               "org2examplecom": {},
```
Then I do channelsign,channelupdate

               
```
VM1:
project# ./minifab channelsign,channelupdate
```
Then I am trying to create a channel on VM2 and also make changes 

```
VM2:
project#./minifab create -c secondchannel
project#./minifab join
project#./minifab channelquery
project#nano ./vars/secondchannel_config.json
```
Changing max_message_count and timout to 50 and 20s accordingly

```
 "value": {
              "absolute_max_bytes": 103809024,
              "max_message_count": 50,
              "preferred_max_bytes": 524288
            },
            "version": "0"
          },
          "BatchTimeout": {
            "mod_policy": "Admins",
            "value": {
              "timeout": "20s"
            },
            "version": "0"
          }, 
```

### Then I get the error 
```
VM2:
project#./minifab channelsign,channelupdate
Minifab Execution Context:
    FABRIC_RELEASE=2.1
    CHANNEL_NAME=secondchannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=true
    CURRENT_ORG=org2.example.com
    HOST_ADDRESSES=192.168.0.111
    WORKING_DIRECTORY: /home/user/go/src/github.com/hyperledger/project
..
# Preparing for the following operations: *********************
  verify options, channel signoff, channel update
........
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  channel signoff
......
# Running operation: ******************************************
  channel update
.
# Select a peer and orderer for channel query. ****************
  Unexpected failure during module execution.
  Traceback (most recent call last):
    File "/usr/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 146, in run
      res = self._execute()
    File "/usr/lib/python3.8/site-packages/ansible/executor/task_executor.py", line 587, in _execute
      self._task.post_validate(templar=templar)
    File "/usr/lib/python3.8/site-packages/ansible/playbook/task.py", line 296, in post_validate
      super(Task, self).post_validate(templar)
    File "/usr/lib/python3.8/site-packages/ansible/playbook/base.py", line 431, in post_validate
      value = templar.template(getattr(self, name))
    File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 618, in template
      d[k] = self.template(
    File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 572, in template
      result = self.do_template(
    File "/usr/lib/python3.8/site-packages/ansible/template/__init__.py", line 837, in do_template
      res = j2_concat(rf)
    File "<template>", line 12, in root
    File "/usr/lib/python3.8/site-packages/ansible/plugins/filter/core.py", line 235, in rand
      return r.choice(end)
    File "/usr/lib/python3.8/random.py", line 290, in choice
      raise IndexError('Cannot choose from an empty sequence') from None
  IndexError: Cannot choose from an empty sequence

# STATS *******************************************************
minifab: ok=24  failed=1

real    0m18.263s
user    0m16.772s
sys     0m1.965s

```
[files.zip](https://github.com/litong01/minifabric/files/4717395/files.zip)

**Comment by aguel** [comment]
### I supposed when you do: 
```
minifab channelquery -c systemchannel
``` 
it returns an empty JSON file which normally implies a non-existing channel.

### When you started your fabric network with:
```
minifab up -e true
```
without specifying a channel, it therefore defaults to **"mychannel"**  

-  You can quickly verify the channel name in the **Minifab Context**

**Comment by Tsine** [comment]
systemchannel is the ordering service network configuration channel. Bellow is certtxgen.sh for example
```
#!/bin/bash
cd $FABRIC_CFG_PATH
cryptogen generate --config crypto-config.yaml --output keyfiles
configtxgen -profile OrdererGenesis -outputBlock genesis.block -channelID systemchannel

  configtxgen -printOrg org0examplecom > JoinRequest_org0examplecom.json
#   export ADMINCERT=$(cat /etc/hyperledger/fabric/keyfiles/peerOrganizations/org0.example.com/users/Admin@org0.example.com/msp/signcerts/Admin@org0.example.com-cert.pem | base64)
#   jq 'del(.values.MSP.value.config.fabric_node_ous)' JoinRequest_org0examplecom.json |\
#   jq --arg admincert "$ADMINCERT" '.values.MSP.value.config.admins[0] |= . + $admincert' > OrgJoinRequest_org0examplecom.json

#   rm -f JoinRequest_org0examplecom.json
  configtxgen -printOrg org1examplecom > JoinRequest_org1examplecom.json
#   export ADMINCERT=$(cat /etc/hyperledger/fabric/keyfiles/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem | base64)
#   jq 'del(.values.MSP.value.config.fabric_node_ous)' JoinRequest_org1examplecom.json |\
#   jq --arg admincert "$ADMINCERT" '.values.MSP.value.config.admins[0] |= . + $admincert' > OrgJoinRequest_org1examplecom.json

#   rm -f JoinRequest_org1examplecom.json

```

**Comment by aguel** [comment]
Sorry for the misunderstanding, what I mean is I think minifab channelquery command supports only the peer channels in context and not the internal channel systemchannel. Hence when you do the `minifab channelquery -c systemchannel` it detects the channel doesn't exist therefore generating the empty JSON. But i maybe wrong, maybe the author can explain better.

**Comment by Tsine** [comment]
Strange . The bellow steps work without any issues 
`project# docker exec cli /vars/run/fetchsystemchannel.sh`
**add a new org to the consortium** 
`project# ./minifab channelsign,channelupdate`

**Then if you do channelqeury with -c  systemchannel it works ** 
`project#./minifab channelquery -c systemchannel`

**Comment by litong01** [comment]
@Tsine where did you get fetchsystemchannel.sh file?
@aguel The problem with getting system channel configuration being empty is due to the permission errors. The identity used to fetch channel configuration was not orderer admin, it was one of the peer org admin, that is why it failed. Let me think about this and see how we can get the systemchannel configuration very smoothly as well.

**Comment by litong01** [comment]
@aguel @Tsine I've made changes to allow system channel query as well. Simply use -c systemchannel to get the system channel configuration json file.

**Comment by Tsine** [comment]
@litong01  that exactly why I made the fetchsystemchannel.sh so I can run the channel query as an orderer. 
The file   fetchsystemchannel.sh I build it using peer commands and used orderer admin instead of organization admin so i have permissions to do it .

**Comment by litong01** [comment]
@Tsine with the latest change, you do not have to do that. specify -c systemchannel will get you the systemchannel configuration.

**Comment by Tsine** [comment]
But the main problem also was the channelupdate from another machine . I will try your fix but I think its not related to other vms Python errors while channelupdate .

My testing pointed me that maybe something is missing so it ends up making an empty sequence maybe the orderers  even if node import worked. 
 IndexError: Cannot choose from an empty sequence

From  minifabric/playbooks/ops/channelupdate/apply.yaml
```

- name: Select a peer and orderer for channel query.
  set_fact:
    actingpeer: "{{ None }}"
    actingorderer: "{{ allorderers | random }}"
    isuffix: "{{ (fabric.release is version('2.0', '>='))|ternary('2', '')}}"
```

**Comment by litong01** [comment]
@Tsine the steps that you took seems very complex. Seems to me that you are trying to make a new org be able to create new channels. Normally, it is the job of the orderer system to create new channels, even though original starter of the fabric network (like org0, org1) can create application channels by default. So the scope of the things are a bit different in your case. To be able to create a new channel, the Admin of the new org and the org its self have to be part of the system channel. So the update has to be made in the system channel. This is different comparing to an application channel.

if you've updated the system channel successfully with the new org, then you should be able to create the new channel using the new org Admin credentials.

**Comment by Tsine** [comment]
@litong01  that why I added new organization (in this case Org2 to the systemchannel) so Org2 can create a channel . If you look i did systermchannel update adding Org2 to the consortium. 

Sorry for not being clear . I can successfully create a channel from VM2  Org2 without any issue .

The problem is "channelupdate" command when changing channel config.

The steps show clearly that fabric does return any error while creating the channel.

**Comment by litong01** [comment]
@Tsine I think that the orderer node selection probably was not done right, I've reworked that part a little bit and think that you will be able to do that.

**Comment by Tsine** [comment]
Thanks !
I will test it tomorrow and i will come back with results

**Comment by Tsine** [comment]
I can query the system config with success.
`./minifab channelquery -c systemchannel`
I include org2 to the consortium of SampleConsortium creating "org2-example-com" then
./minifab channelsign,channeupdate 

```
# Run the channel update script on cli container **************
  non-zero return code
  2020-06-03 06:04:31.407 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
  Error: got unexpected status: BAD_REQUEST -- error applying config update to existing channel 'systemchannel': error authorizing update: error validating ReadSet: proposed update requires that key [Group]  /Channel/Application be at version 1, but it is currently at version 0

```
I will deep dive into documentation and I will come back . It looks obvious but whatever I tried in systemchannel_config.json give me the same error

**Comment by Tsine** [comment]
After the latest commit everything works .
I would suggest to anyone to read the updated docs describing the steps which are included in the latest commit.
