### ISSUE TITLE
Feature: Ability to choose or switch Solo/Raft in ordering service

### ISSUE THREAD

**Issue by aguel** [litong01/minifabric#24]
Possibility to specify ordering service consensus Solo/Raft/etc in the CLI options or spec.yaml.

**Comment by davidkhala** [comment]
BTW, Solo is not recommended now, and if there is case that only single orderer is needed, configure raft cluster with orderer number == 1

**Comment by aguel** [comment]
Thanks. Is it by default minifabric uses raft?

**Comment by litong01** [comment]
@aguel minifabric does not support kafka. It always uses raft. In my opinion, kafka simply makes things way too complex. People are moving away from it.

**Comment by litong01** [comment]
As @davidkhala indicated, specify only one orderer node will make your system a solo type of orderering. I would say minifabric supports that from day one.

**Comment by aguel** [comment]
Thank you for the explanation and clarification
