### ISSUE TITLE
Add azure pipeline status badge

### ISSUE THREAD

**Issue by davidkhala** [litong01/minifabric#26]
Notice we have configured azure pipeline. 
We could add badge to indicate latest build status in README

**Comment by litong01** [comment]
PR will be great @davidkhala

**Comment by davidkhala** [comment]
@litong01 The website layout of Azure pipeline seems changed. I could not find a out-of-box badge svg link in pipeline history page.

**Comment by davidkhala** [comment]
Otherwise it is due to access control that non code owner use could not see some of menu.

**Comment by litong01** [comment]
@davidkhala I am not really following what you are saying. What information will you need to do a PR?

**Comment by davidkhala** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/create-first-pipeline?view=azure-devops&tabs=java%2Cyaml%2Cbrowser%2Ctfs-2018-2#add-a-status-badge-to-your-repository

Most tutorial have statement like
"In the context menu for the pipeline, select Status badge."

while I could not see the context menu

Reply to "our readme.md file will have a piece of information indicating what has happened in the latest commit?"

Concisely speaking, we will have a status light about whether the auto-build based on last commit is success or not.
