### ISSUE TITLE
Channel Creation Error

### ISSUE THREAD

**Issue by edkaz** [litong01/minifabric#27]
Hello

I received the following error while trying to set up a new hyperledger supply chain network. This is the first time that I have gotten this error using minifab as it usually means trying to create a channel with the wrong 'admin' credentials. Is that the case here? How do I fix it in minifab. 

```[bash]
# Run the channel creation script on cli container ************
  non-zero return code
  2020-06-08 07:18:09.411 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
  2020-06-08 07:18:09.446 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /vars/configtx.yaml
  2020-06-08 07:18:09.446 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 003 Generating new channel configtx
  2020-06-08 07:18:09.515 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 004 Writing new channel tx
  2020-06-08 07:18:09.704 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
  Error: got unexpected status: BAD_REQUEST -- error validating channel creation transaction for new channel 'kasese', could not successfully apply update to template configuration: error authorizing update: error validating DeltaSet: policy for [Group]  /Channel/Application not satisfied: implicit policy evaluation failed - 0 sub-policies were satisfied, but this policy requires 1 of the 'Admins' sub-policies to be satisfied
```

Thanks - Ed

**Comment by litong01** [comment]
@edkaz can you detail the steps you took so that someone can recreate the issue?

**Comment by edkaz** [comment]
Hello

**Comment by litong01** [comment]
@edkaz ok, I see what the problem is here. You have basically one org for everything. Your org is node-1.kasese.com, which gets used for both peer and orderer nodes. This actually causes issues because same mspid (node-1-kasese-com) in your case use different tlsca cert, this got the system really mixed up when looking for cert files. If you use different org for your orderer nodes, you should be fine.  see an example below. BTW there really is no good reason why you need 4 ca nodes for the same organization, normally number of orderer nodes should be an odd number such as 3, 5 etc.

```
fabric:
  cas:
  #========  KASESE TDN Certificate Authorities  ===============
  - "peer-1-ca.node-1.kasese.com"
  - "peer-2-ca.node-1.kasese.com"
  - "peer-3-ca.node-1.kasese.com"
  - "peer-4-ca.node-1.kasese.com"

  peers: 
  #========  KASESE TDN Peer Nodes  ============================
  - "peer-1.node-1.kasese.com"
  - "peer-2.node-1.kasese.com"
  - "peer-3.node-1.kasese.com"
  - "peer-4.node-1.kasese.com"

  orderers:
  #========  KASESE TDN Orderer Nodes  ==========================
  - "orderer-1.kasese.com"
  - "orderer-2.kasese.com"
  
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
```

**Comment by litong01** [comment]
The said above does not mean that fabric does not allow you to use same org name for both peer and orderer org. It is just that minifabric uses the org name to create mspid, if mspid somehow can be created differently for peer and orderer, then I suspect it may work fine. at present, minifabric creates mspid by replace character dot (.) with dash (-), alternatively, we could create mspid by adding a prefix such as peerOrg for peer and ordererOrg for orderer, then things may work, but even in same org name for both peer and orderer org, the tlsca will be different. they will still be considered two different orgs, so to avoid such issues, use different org names for peer and orderer.

**Comment by edkaz** [comment]
Hello
Thank you for your quick help. I can easily reorganise the spec. to fix the problem. 
Cheers  - Ed
