### ISSUE TITLE
Connection Profiles for Chaincode

### ISSUE THREAD

**Issue by edkaz** [litong01/minifabric#28]
Hello 
Is there an easy way to generate `Connection Profiles` for interacting with chaincode?

Cheers - Ed

**Comment by edkaz** [comment]
Hello

**Comment by aguel** [comment]
@edkaz Not sure if I understand your question correctly but connection profiles are automatically generated under **/vars/profiles** or if you want to re-generate it, you can do the "profilegen" minifab command

**Comment by edkaz** [comment]
@aguel   
No, I think the misunderstanding is mine and I may have missed the part where that was explained. I did not have a **/vars/profile** before but ran **minifab profilegen** and now I do. Thank you.
At what step are profiles generated?

**Comment by aguel** [comment]
@edkaz they are part of the sequence of commands automatically executed when you do "**minifab up**"

**Comment by edkaz** [comment]
@aguel. Hmmm interesting. I did not get a **/vars/profile** directory when I ran minifab up but now I at least know how to fix the problem. Thank you so much for your help. Best Regards - Ed

**Comment by edkaz** [comment]
Of course the answer is that minifab already generates all of the necessary connection profiles and that they can be found in **/vars/profiles**. My sincere thanks to @aguel who pointed this out. 
- Ed

**Comment by litong01** [comment]
@edkaz it has to. otherwise, things actually broke. This is the code where I define what `minifab up` does. https://github.com/litong01/minifabric/blob/master/scripts/mainfuncs.sh#L11, you can see L11 and L22 make up the commands being called when one run `minifab up` which includes profilegen.

**Comment by edkaz** [comment]
@litong01 Hello Tong Li, Now that you put it that way and looking at your code its obvious why connections profiles are needed. I had an abnormal **/vars/** for one of my test networks where for whatever reason the **/profiles** was missing. I've tried to recreate the state but so far I can't - which is good news I think. But if I encounter the issue again, I'll let you know.

**Comment by litong01** [comment]
@edkaz you probably want to do a `minifab cleanup` to reset whole thing and probably refresh minifab by doing `docker pull hfrd/minifab:latest`
