### ISSUE TITLE
Minifab is failing with 2.0 version

### ISSUE THREAD

**Issue by Ram-srini** [litong01/minifabric#29]
Hello Tong,

I am getting error while bring up fabric network fabric version 2.0.

# Fabric network **************************************************************************************
  * minifab
    setting up
............................................................

# STATS ***********************************************************************************************
minifab: ok=65  failed=0
...
# Fabric operations ***********************************************************************************
  * minifab
    channel create, channel join, anchor update, profile generation, cc install, cc approve, cc commit, discover
.....................................................
# Run the anchor update script on cli container *******************************************************
  * minifab
    non-zero return code
    2020-06-15 06:20:59.626 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
    2020-06-15 06:20:59.652 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /vars/configtx.yaml
    2020-06-15 06:20:59.652 UTC [common.tools.configtxgen] doOutputAnchorPeersUpdate -> INFO 003 Generating anchor peer update
    2020-06-15 06:20:59.653 UTC [common.tools.configtxgen] doOutputAnchorPeersUpdate -> INFO 004 Writing anchor peer update
    2020-06-15 06:20:59.694 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
    Error: got unexpected status: BAD_REQUEST -- Consortium config value missing

# STATS ***********************************************************************************************
minifab: ok=68  failed=1
Running Nodes:
cli:
ca1.org1.example.com:7054/tcp
ca1.org0.example.com:7054/tcp
orderer3.example.com:7050/tcp
orderer2.example.com:7050/tcp
orderer1.example.com:7050/tcp
peer2.org1.example.com:7051/tcp
peer1.org1.example.com:7051/tcp
peer2.org0.example.com:7051/tcp
peer1.org0.example.com:7051/tcp
minifab:

Minifab version 0.1.0
command used: minifab -u
Fabric version used 2.0

**Comment by litong01** [comment]
Please try the latest release.

**Comment by litong01** [comment]
@Ram-srini can you update according to what I updated above?

**Comment by litong01** [comment]
no following up, closing this. @Ram-srini
