### ISSUE TITLE
Use on MacOS

### ISSUE THREAD

**Issue by zcqzcg** [litong01/minifabric#3]
The script part on line 3 'ADDRS=...' for macos could be modified to this:

`ADDRS=$(ip -4 a | grep -v '\.1/' | grep inet | tr -s ' ' | cut -d ' ' -f 2 | cut -d '/' -f 1 | paste -sd ',' -)`

And if you don't have an `ip` command in your macos, please try:
`brew install iproute2mac`

------

Error msg 'docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/home/main.sh\": stat /home/main.sh: no such file or directory": unknown.'

Fix: `docker pull hfrd/minifab` for the newer version.

------

Error 'Error: failed to read chaincode package at 'simple_go_1.0.tar.gz': open simple_go_1.0.tar.gz: no such file or directory' on the process

Fix: `minifab down && minifab cleanup &&  minifab up`
This is also because the GFW will block some of the golang pkgs, it's wonderful if you can use a goproxy on the cli(fabric-tools) containner.

--------

I am trying to run fabric-2.0 with minifab in MacOS, I will continue on updating this issue until it fits on MacOS.

**Comment by litong01** [comment]
David,
   Thanks for the suggestion, I looked at that and wonder if we should try to use ifconfig command instead which should work for both linux and OS X? I am also thinking how we can do that for windows, only small piece of script, once these are good, we should be able to run minifabric on more platforms. What do you think? If you find good solution, please do a pull request.

like this.
` ifconfig | grep 'inet '`

**Comment by litong01** [comment]
seems this would work for both OS x and linux

`ADDRS=(ifconfig | grep 'inet ' | grep -v '\.1 ' | tr -s ' ' | cut -d ' ' -f 2 | cut -d '/' -f 1 | paste  -sd "," -)`

**Comment by litong01** [comment]
seems this will work for both OS X and Linux.

`ADDRS=$(ifconfig | grep 'inet ' | grep -v '\.1 ' | tr -s ' ' | awk '{$1=$1};1' | cut -d ' ' -f 2|cut -d '/' -f 1|paste -sd "," -)`

**Comment by litong01** [comment]
let me make this change so that we can at least support both OS X and Linux for now.

**Comment by litong01** [comment]
The changes have been made to the minifab script, please test and close if works.

**Comment by zcqzcg** [comment]
Hi Mr.Li, 
That works on OS X and Linux.
And I don't think work with windows is a good choice.
Because dev on windows with golang and docker is a disaster, let's just stick to the Unix/Linux for now.

**Comment by litong01** [comment]
hmmm. On windows it will be just docker, not golang. The chaincode will be
running inside a container and if the windows system has golang or not does
not really matter. It will be actually quite nice to make it working on
windows even if it is a different script.

Thanks.

Tong Li
IBM Open Technology
