### ISSUE TITLE
Node JS - Missing certificates for certificateAuthorities in both .json and .yaml connection profiles. 

### ISSUE THREAD

**Issue by edkaz** [litong01/minifabric#32]
Hello,
This issue looks like it may be a repeat of issue #13 but I have the same problem. I've  pulled the most recent version of minifab from the repository and regenerated the profiles. The connection profiles for the __GO SDK__ and the __Python SDK__ are okay but the Node SDK fails to generate the certificates for __certificateAuthorities__. 

Is there a workaround?

**Comment by davidkhala** [comment]
@edkaz Would you mind provide more details?

**Comment by edkaz** [comment]
Hello David, 
I saw this PR and was wondering about it. I'm using Minifab on MacOS 10.15.5 Catalina and pulled the latest version about  2 hours from the ````README.md``` file

**Comment by davidkhala** [comment]
Do you mean `certificateAuthorities` sections not found in the output connection profile file? Or you could see it in file but sdk-node could not detect?

**Comment by edkaz** [comment]
The ```certificateAuthorities``` sections are not found in the output connection profile. 
Thanks Ed

**Comment by litong01** [comment]
@edkaz @davidkhala , if you guys work together on this with a PR, that will be fantastic.

**Comment by edkaz** [comment]
@litong01 I can try but I also have a large project to deploy in beta in about a week and probably won't get the time. However, I wanted minifab to generate the profiles so that I don't have to constantly patch certificateAuthorities and their CERTS.
But will do what we can.

**Comment by aguel** [comment]
I think i already made a PR for this and was already merged. Did you pull the latest minifab image @edkaz ?

**Comment by edkaz** [comment]
Hello 
I thought the PR was already merged as well. I downloaded the the version pointed to by the ```README.md``` docs using cURL as follows ```curl -o minifab -sL https://tinyurl.com/twrt8zv```.   So I am assuming this is the latest version.

**Comment by aguel** [comment]
You also have to update the latest minifabric docker image, just do “docker pull hfrd/minifab:latest”

**Comment by edkaz** [comment]
Oh of course! Let me try that.

**Comment by edkaz** [comment]
I pulled the new docker image and now everything works as expected.
My sincerest thanks to you all. 
Regards - Ed
