### ISSUE TITLE
Branch, release, version 

### ISSUE THREAD

**Issue by davidkhala** [litong01/minifabric#34]
Now minifabric have a master branch with additional pre-release branch 0.1.0 and 0.2.0
And in document we have seen some of specific 1.4.1, 1.4.2, 2.0 etc

I wonder if we could manage branch in this way:
- Align with Fabric LTS control, we keep at most 2 LTS and 1 Dev (as master)
- Document only illustrate for current branch, thus you will never see words 1.4.x in master branch nor 2.0 in 0.1.0 branch

**Comment by litong01** [comment]
@davidkhala I think these are good ideas, can you start putting up PRs?

**Comment by litong01** [comment]
@davidkhala not seeing any action on this, I am closing this one.
