### ISSUE TITLE
minifab up error: Error: failed to read chaincode package at 'simple_go_1.0.tar.gz'

### ISSUE THREAD

**Issue by justalittlenoob** [litong01/minifabric#39]
I think minifab is  a great tool. But when I tried it for the first time, I had some trouble.   
Any advice would be appreciated.  

I have tired, 
1. two proxy (`goproxy: "https://goproxy.cn,direct"` and `goproxy: "https://goproxy.io,direct"`) in spec.yaml file , but neither work.  
2. add `-e GOPROXY="https://goproxy.cn"` in `docker run` command in minifab file, doesn't work.   

Here is the [spec.txt](https://github.com/litong01/minifabric/files/4879938/spec.txt) file i am using. (`yaml` file type is not support when attached, so i change it to `txt` type)

`root@pengfei-desk:/home/pengfei/bc/minifabric# ./minifab up`
>Minifab Execution Context:
    FABRIC_RELEASE=2.1
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=172.16.113.194
    WORKING_DIRECTORY: /home/pengfei/bc/minifabric
Fabric network **************************************************************************************
  * minifab
    setting up
....................................

STATS ***********************************************************************************************
minifab: ok=41  failed=0
..
Fabric operations ***********************************************************************************
  * minifab
    channel create, channel join, anchor update, profile generation, cc install, cc approve, cc commit, cc initialize, discover
...................................................................................................
Run the chaincode install script on cli container ***************************************************
  * minifab
    non-zero return code
    **go: github.com/golang/protobuf@v1.3.1: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.3.1.mod": dial tcp 216.58.200.49:443: i/o timeout
    Error: failed to normalize chaincode path: 'go list' failed with: go: github.com/golang/protobuf@v1.3.1: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.3.1.mod": dial tcp 216.58.200.49:443: i/o timeout: exit status 1
    Error: failed to read chaincode package at 'simple_go_1.0.tar.gz': open simple_go_1.0.tar.gz: no such file or directory**

STATS ***********************************************************************************************
minifab: ok=119 failed=1
Running Nodes:
cli:
ca1.org1.example.com:7054/tcp
ca1.org0.example.com:7054/tcp
orderer3.example.com:7050/tcp
orderer2.example.com:7050/tcp
orderer1.example.com:7050/tcp
peer2.org1.example.com:7051/tcp
peer1.org1.example.com:7051/tcp
peer2.org0.example.com:7051/tcp
peer1.org0.example.com:7051/tcp
minifab:
intelligent_feynman:
vigilant_ganguly:
hardcore_wiles:

real    1m34.144s
user    0m35.119s
sys     0m4.582s

`root@pengfei-desk:/home/pengfei/bc/minifabric# docker ps -a`
>CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS                   PORTS               NAMES
57a8336850d6        hyperledger/fabric-tools:2.1     "/bin/sh"                17 minutes ago      Up 17 minutes                                cli
f1d06c0af4fe        hyperledger/fabric-ca:1.4        "/bin/sh -c 'fabric-…"   17 minutes ago      Up 17 minutes            7054/tcp            ca1.org1.example.com
b8b383c2e121        hyperledger/fabric-ca:1.4        "/bin/sh -c 'fabric-…"   17 minutes ago      Up 17 minutes            7054/tcp            ca1.org0.example.com
bfb22e9622e3        hyperledger/fabric-orderer:2.1   "orderer"                17 minutes ago      Up 17 minutes            7050/tcp            orderer3.example.com
189cf3211283        hyperledger/fabric-orderer:2.1   "orderer"                17 minutes ago      Up 17 minutes            7050/tcp            orderer2.example.com
12e09c7ef631        hyperledger/fabric-orderer:2.1   "orderer"                17 minutes ago      Up 17 minutes            7050/tcp            orderer1.example.com
2517e9718a71        hyperledger/fabric-peer:2.1      "peer node start"        17 minutes ago      Up 17 minutes            7051/tcp            peer2.org1.example.com
343bc701f9fc        hyperledger/fabric-peer:2.1      "peer node start"        17 minutes ago      Up 17 minutes            7051/tcp            peer1.org1.example.com
f8d5bc4998a2        hyperledger/fabric-peer:2.1      "peer node start"        17 minutes ago      Up 17 minutes            7051/tcp            peer2.org0.example.com
ede7f0a8de21        hyperledger/fabric-peer:2.1      "peer node start"        17 minutes ago      Up 17 minutes            7051/tcp            peer1.org0.example.com
  
`root@pengfei-desk:/home/pengfei/bc/minifabric# docker exec -it cli bash`
`bash-5.0# env`
>HOSTNAME=cli
FABRIC_CFG_PATH=/etc/hyperledger/fabric
PWD=/go
HOME=/root
GOLANG_VERSION=1.14.1
TERM=xterm
SHLVL=1
PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GOPATH=/go
_=/usr/bin/env

**Comment by litong01** [comment]
this is actually an issue during the chaincode install. I have very little idea about the golang proxy in china. you probably can try the following, not using golang chaincode to avoid go proxy issues. Here is how to try

```
minifab cleanup
minifab netup
minifab install -l node
```

The latest command is to ask minifabric install default chaincode in node.

BTW, I've also used this in the spec.yaml file. and it all worked just fine.

goproxy: "https://goproxy.cn,direct"

I've also noticed that your spec is a txt file, not spec.yaml, that is probably why your own spec file was not used.

**Comment by justalittlenoob** [comment]
@litong01   
Hi, thanks for your advice.  
1. I am using `spec.yaml` not `spec.txt`. (the `txt` file type is because github doesn't support `yaml` file attached)
2. Because my host machine is behind a network proxy, so http proxy, https proxy and no proxy are added to `/etc/environment` and `~/.docker/config.json`. Is there any other config file need the proxy setting?
3. According to your advice, after running the four command `minifab down`, `minifab cleanup`, `minifab netup`, `minifab install -l node` , i got a new error.
> Run the chaincode install script on cli container ***************************************************
    minifab
    non-zero return code
    **Error: chaincode install failed with status: 500 - error in simulation: failed to execute transaction 8f6a71df6059eb08fcac74a2716236f5cd06637702710ec695ed28dbc7629b66: error sending: timeout expired while executing transaction**
4. `docker logs peer1.org0.example.com`
>github.com/hyperledger/fabric/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1
        /go/src/github.com/hyperledger/fabric/vendor/google.golang.org/grpc/server.go:746
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1373
**error sending
failed to execute transaction 8f6a71df6059eb08fcac74a2716236f5cd06637702710ec695ed28dbc7629b66**
github.com/hyperledger/fabric/core/chaincode.processChaincodeExecutionResult
        /go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:161
github.com/hyperledger/fabric/core/chaincode.(*ChaincodeSupport).Execute
        /go/src/github.com/hyperledger/fabric/core/chaincode/chaincode_support.go:156

**Comment by litong01** [comment]
@justalittlenoob you probably can try to ping the proxy goproxy.cn and see if you can get through. I am not sure what you mean by this
```add -e GOPROXY="https://goproxy.cn" in docker run command in minifab file, doesn't work.```
The proxy setting should be in your spec.yaml file as the example has demostrated. 

If you can ping goproxy.cn from your machine and change the setting in your spec.yaml file as the example demostrated, you should be ok.

Here is the example spec.yaml file with goproxy.cn


```
fabric:
  cas:
  - "ca1.org0.example.com"
  - "ca1.org1.example.com"
  peers: 
  - "peer1.org0.example.com"
  - "peer2.org0.example.com"
  - "peer1.org1.example.com"
  - "peer2.org1.example.com"
  orderers:
  - "orderer1.example.com"
  - "orderer2.example.com"
  - "orderer3.example.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
    goproxy: "https://goproxy.cn,direct"
```

**Comment by pkirkinezis** [comment]
I had the same problem on one of my server . Check that your machine has access to the internet. 
In the up or netup process it tried to download https://proxy.golang.org/github.com/golang/protobuf/@v/v1.3.1.mod . 
If you are offline or something blocks(firewall maybe ) the download of https://proxy.golang.org/github.com/golang/protobuf/@v/v1.3.1.mod then you have no luck instantiating the network

**Comment by justalittlenoob** [comment]
It seems that the proxy of my company has some problems. I'll apply for some proxy permissions first, and then try again according to your suggestions. Whether it's successful or not, I'll come back and tell you.

**Comment by justalittlenoob** [comment]
It indeed a enterprise proxy problem. The problem is solved.
