### ISSUE TITLE
Commit chaincode on multiorganization channel 

### ISSUE THREAD

**Issue by pkirkinezis** [litong01/minifabric#41]
Hi , 
It's not 100% issue maybe .
server 1: ORG0 +ORDERERS 
server 2: ORG1 
server 3: ORG2
When installing a chain code on a +3 organizations channel((from different servers)) as the documentation states you have to approve from all the organizations and then send a final  commit to  all the organizations from one peer .
The endorsement policy is to majority.

From the documentation on fabric sample is run commit for 2 orgs with specific tls key.
[read-the-docs](https://hyperledger-fabric.readthedocs.io/en/release-2.0/build_network.html.)

```
# this commits the chaincode definition to the channel
peer lifecycle chaincode commit -o orderer.example.com:7050 --channelID $CHANNEL_NAME --name mycc --version 1.0 --sequence 1 --init-required --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem --peerAddresses peer0.org1.example.com:7051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt --peerAddresses peer0.org2.example.com:9051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
```
### So in our situation in minifabric.
If the organizations are on different servers  you have to exchange tls keys of course between servers .
But the cccommit.sh script produced by minifab includes only the peers existing on that server and not all the peers in the network. 
So when you try commit with the bellow produced cccommit.sh 

```
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_ID=cli
export CORE_PEER_ADDRESS=192.168.69.18:7051
export CORE_PEER_TLS_ROOTCERT_FILE=/vars/keyfiles/peerOrganizations/org0.example.com/peers/peer1.org0.example.com/tls/ca.crt
export CORE_PEER_LOCALMSPID=org0-example-com
export CORE_PEER_MSPCONFIGPATH=/vars/keyfiles/peerOrganizations/org0.example.com/users/Admin@org0.example.com/msp
export ORDERER_ADDRESS=192.168.69.18:7050
export ORDERER_TLS_CA=/vars/keyfiles/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/ca.crt
SID=$(peer lifecycle chaincode querycommitted -C mychannel -O json \
  | jq -r '.chaincode_definitions|.[]|select(.name=="simple")|.sequence' || true)

if [[ -z $SID ]]; then
  SEQUENCE=1
else
  SEQUENCE=$((1+$SID))
fi

peer lifecycle chaincode commit -o $ORDERER_ADDRESS --channelID mychannel\
  --name simple --version 1.0 --sequence $SEQUENCE \
  --peerAddresses 192.168.69.18:7051 \
  --tlsRootCertFiles /vars/keyfiles/peerOrganizations/org0.example.com/peers/peer2.org0.example.com/tls/ca.crt \
  --init-required \
  --cafile $ORDERER_TLS_CA --tls

```
**You get endorsement policy failure .** 

Because one peer has to send a final commit to all organizations we have to include these organizations to cccommit.sh 

What is the best way to approach this inside mini fabric . We have to be able to generate a cccommit.sh including all the peers 

Something like : 
```
peer lifecycle chaincode commit -o $ORDERER_ADDRESS --channelID mychannel \
  --name simple --version 1.0 --sequence $SEQUENCE \
  --peerAddresses 192.168.69.18:7051 \
  --tlsRootCertFiles /vars/keyfiles/peerOrganizations/org0.example.com/peers/peer2.org0.example.com/tls/ca.crt \
  --peerAddresses 192.168.69.19:7051 \
  --tlsRootCertFiles /vars/keyfiles/peerOrganizations/org0.example.com/peers/peer2.org1.example.com/tls/ca.crt \
  --peerAddresses192.168.69.20:7051 \
  --tlsRootCertFiles /vars/keyfiles/peerOrganizations/org0.example.com/peers/peer2.org2.example.com/tls/ca.crt \
  --init-required \
  --cafile $ORDERER_TLS_CA --tls
```

**Comment by litong01** [comment]
@pkirkinezis you need to commit what you approve. Also when more orgs involved, you have to pass around the approved the proposal. Otherwise, it wont work.

**Comment by pkirkinezis** [comment]
> 
> 
> @pkirkinezis you need to commit what you approve. Also when more orgs involved, you have to pass around the approved the proposal. Otherwise, it wont work.
Firstly i approve the proposal from all the orgs  (3 in our example). 
The approval is distributed correctly . 
`peer lifecycle chaincode checkcommitreadiness `
Returns true for all the orgs  . 
The problem is the commit. 

As the documentation states you have to send a final commit to all the organizations involved from one peer .  
If you check above the docs 

### peer lifecycle chaincode commit example
Once a sufficient number of organizations approve a chaincode definition for their organizations (a majority by default), one organization can commit the definition the channel using the peer lifecycle chaincode commit command:

This command needs to target the peers of other organizations on the channel to collect their organization endorsement for the definition.


```
export ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem

peer lifecycle chaincode commit -o orderer.example.com:7050 --channelID mychannel --name mycc --version 1.0 --sequence 1 --init-required --tls --cafile $ORDERER_CA --peerAddresses peer0.org1.example.com:7051 --peerAddresses peer0.org2.example.com:9051

2019-03-18 16:14:27.258 UTC [chaincodeCmd] ClientWait -> INFO 001 txid [b6f657a14689b27d69a50f39590b3949906b5a426f9d7f0dcee557f775e17882] committed with status (VALID) at peer0.org2.example.com:9051
2019-03-18 16:14:27.321 UTC [chaincodeCmd] ClientWait -> INFO 002 txid [b6f657a14689b27d69a50f39590b3949906b5a426f9d7f0dcee557f775e17882] committed with status (VALID) at peer0.org1.example.com:7051
```

**Comment by pkirkinezis** [comment]
Is there anything i am missing here . 
I am trying to understand the "you need to commit what you approve. Also when more orgs involved, you have to pass around the approved the proposal." 
What do you mean pass around the approved proposal ?

**Comment by litong01** [comment]
@pkirkinezis when you approve chaincode, you are producing a file, that contains signatures of approving org. that file needs to be placed on other server, then the admin on that server can also approve, while you are approving things, nothing happens to the ledger, the only thing happened is the signed file, which need to be pass from one to the other for signing. Once all required orgs signed it, then one org can approve. Watch what gets produced, then passing that to the other server.

**Comment by pkirkinezis** [comment]
In the channelsign I new that a file is produced  .Could you tell me what file is produced while running ./minifab approve to check it in the morning . 
Thanks in advance .

**Comment by pkirkinezis** [comment]
I found these two separate approaches . One is latest explaining the installation ...the other is 1.4 and talks about a cdn files produced that is signed from organizations. 

1. https://hyperledger-fabric.readthedocs.io/en/release-2.2/chaincode_lifecycle.html#step-three-approve-a-chaincode-definition-for-your-organization
2. https://hyperledger-fabric.readthedocs.io/en/release-1.4/chaincode4noah.html

As for mini fabric it works generating a tar.gz file for the chaincode you are installing .

**Comment by litong01** [comment]
@pkirkinezis I do not think that is the issue you have. you really need to make sure that all orgs have been added into the channel correctly. The sign of you did that correctly is the joining peers in the new org to a channel went successfully. Otherwise, your new org is not in the channel yet. With that being done, you can install whatever chaincode onto the new peers, then approve , with enough of orgs approving it, one org admin can commit, this means some org may not have approved the chaincode, if that is the case, that org's peer can not possibly endorse the tx against the chaincode, only when that org approves the chaincode, the peers will have chaincode containers going. During this whole process, there is no files need to be moved around, only when you do the process of joining a new org, the signed file needs to be moved around for necessary number of orgs to be signed. Here is the link to the file which need to be moved. see this line of code for the file name to be moved for signing when join new orgs. https://github.com/litong01/minifabric/blob/master/playbooks/ops/templates/channelsignoff.j2#L49

**Comment by pkirkinezis** [comment]
> chaincode

Now we are on the same line . Maybe i was not clear in my first comments so my bad.


1. The channel already exists and has 3 orgs successfully joined in the channel (It is correct that I did that by exchanging the sign file between 3 servers and also exchanging JoinRequest file).  

2. Now on this existing channel,with the 3 organizations joined,  first you install the chain code to 3 organizations and approve from all 3 .

3. Final step committing the chain code 
In this final step of committing the new installed chain code you need to run the commit command with all the peerAdresses  in the command . 
So the cccommit.sh file generated by minifabric should include all the peerAdresses from all the orgs in this channel. Like the above.

```
SID=$(peer lifecycle chaincode querycommitted -C telenrstchannel -O json \
  | jq -r '.chaincode_definitions|.[]|select(.name=="myasset")|.sequence' || true)

if [[ -z $SID ]]; then
  SEQUENCE=1
else
  SEQUENCE=$((1+$SID))
fi

peer lifecycle chaincode commit -o $ORDERER_ADDRESS --channelID mychannel \
  --name simple --version 1.0 --sequence $SEQUENCE \
  --peerAddresses 192.168.69.18:7051 \
  --tlsRootCertFiles /vars/keyfiles/peerOrganizations/org0.example.com/peers/peer2.org0.example.com/tls/ca.crt \
  --peerAddresses 192.168.69.19:7051 \
  --tlsRootCertFiles /vars/keyfiles/peerOrganizations/org0.example.com/peers/peer2.org1.example.com/tls/ca.crt \
  --peerAddresses192.168.69.20:7051 \
  --tlsRootCertFiles /vars/keyfiles/peerOrganizations/org0.example.com/peers/peer2.org2.example.com/tls/ca.crt \
  --init-required \
  --cafile $ORDERER_TLS_CA --tls

```

**Comment by litong01** [comment]
@pkirkinezis specific peer address? Why is it necessary? We are currently only selecting one peer randomly from an org. Is there a particular reason why would you want to do that?

**Comment by pkirkinezis** [comment]
Yeah committing a new installed chain code to an existing channel having 3 organizations (on different server each org in the example above ) requires all three orgs in commit command  like the example above i posted.
Basically in multi organization channels `peer  lifecycle chaincode commit` command as stated in the docs and also some other  peer lifecycle chaincode commands need all the  peer adresses  in the command parameters

**Comment by pkirkinezis** [comment]
@litong01 
Could we do the same as  in the invoke command  ? 
If you see in the` ./minifab  invoke` command it uses all the peers found in the folder created by ` ./minfab discover `.

**Comment by litong01** [comment]
@pkirkinezis are you saying each peer will need to be in the commit command? That does not make sense to me.

**Comment by pkirkinezis** [comment]
> @pkirkinezis are you saying each peer will need to be in the commit command? That does not make sense to me.

Its clearly stated in the docs  for the commit command . 
Here :
https://hyperledger-fabric.readthedocs.io/en/release-2.0/build_network.html.
Or Here :
https://hyperledger-fabric.readthedocs.io/en/release-2.0/commands/peerlifecycle.html

**Comment by litong01** [comment]
@pkirkinezis Which section says that? Can you copy & paste the content here? I've looked through these docs multiple times, I think what we have done in the script is correct. We currently already pick one peer from an org for sending the commit command to. It is just that we pick a peer randomly. I am not quite sure what you ask for.

**Comment by pkirkinezis** [comment]
Since both channel members have approved the definition, we can now commit it to the channel using the following command. You can issue this command as either Org1 or Org2. Note that the transaction targets peers in Org1 and Org2 to collect endorsements.

# this commits the chaincode definition to the channel

```
# this commits the chaincode definition to the channel
peer lifecycle chaincode commit -o orderer.example.com:7050 --channelID $CHANNEL_NAME --name mycc --version 1.0 --sequence 1 --init-required --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem --peerAddresses peer0.org1.example.com:7051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt --peerAddresses peer0.org2.example.com:9051 --tlsRootCertFiles /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/ca.crt
```

As you can see in the commit command it has both peer0 Org1 and peer0 Org2

**Comment by pkirkinezis** [comment]
@litong01 
Also here 
peer lifecycle chaincode commit example

Once a sufficient number of organizations approve a chaincode definition for their organizations (a majority by default), one organization can commit the definition the channel using the peer lifecycle chaincode commit command:
    This command needs to target the peers of other organizations on the channel to collect their organization endorsement for the definition.



export ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/example.com/orderers/orderer.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
    ```
    peer lifecycle chaincode commit -o orderer.example.com:7050 --channelID mychannel --name mycc --version 1.0 --sequence 1 --init-required --tls --cafile $ORDERER_CA --peerAddresses peer0.org1.example.com:7051 --peerAddresses peer0.org2.example.com:9051

    2019-03-18 16:14:27.258 UTC [chaincodeCmd] ClientWait -> INFO 001 txid [b6f657a14689b27d69a50f39590b3949906b5a426f9d7f0dcee557f775e17882] committed with status (VALID) at peer0.org2.example.com:9051
    2019-03-18 16:14:27.321 UTC [chaincodeCmd] ClientWait -> INFO 002 txid [b6f657a14689b27d69a50f39
```

**Comment by litong01** [comment]
@pkirkinezis that is how it was implemented in minifabric. when you have two orgs, and using default endorsement policy, you need both to approve. commit works the same way. But consider this case, you have total of 10 orgs with default endorsement policy, that means you need 6 of them to approve and commit, say the 7th and 8th org did not do anything, then the 7th and 8th org peers wont be able to participate in this chaincode txs until the org also do approve and commit.

**Comment by pkirkinezis** [comment]
> 
> 
> @pkirkinezis that is how it was implemented in minifabric. when you have two orgs, and using default endorsement policy, you need both to approve. commit works the same way. But consider this case, you have total of 10 orgs with default endorsement policy, that means you need 6 of them to approve and commit, say the 7th and 8th org did not do anything, then the 7th and 8th org peers wont be able to participate in this chaincode txs until the org also do approve and commit.

That is true but in minifabric it only using one peer org randomly  . 
The point is on commit command that need peerAddresses not only from one peer.
As you said in 10 orgs ...you run approve on all 10 of them one by one .
Then in second step one of the orgs need to run commit command . 
In this commit command you need to include  all peerAdresses of all the orgs 
```

peer lifecycle chaincode commit -o 192.168.69.100:7050 --channelID mychannel --name mycc --version 1.0 --sequence 1 --init-required --tls --cafile $ORDERER_CA
 --peerAddresses 192.168.69.100:7051
 --tlsRootCertFiles /vars/discover/mychannel/org1-example.com/tlscert \
 --peerAddresses192.168.69.101:7051
 --tlsRootCertFiles /vars/discover/mychannel/org2-example.com/tlscert \
 --peerAddresses 192.168.69.102:7051
 --tlsRootCertFiles /vars/discover/mychannel/org3-example.com/tlscert \
 --peerAddresses 192.168.69.103:7051
 --tlsRootCertFiles /vars/discover/mychannel/org4-example.com/tlscert \
 --peerAddresses 192.168.69.104:7051
 --tlsRootCertFiles /vars/discover/mychannel/org5-example.com/tlscert \
 --peerAddresses 192.168.69.105:7051
 --tlsRootCertFiles /vars/discover/mychannel/org6-example.com/tlscert \
 --peerAddresses 192.168.69.106:7051
 --tlsRootCertFiles /vars/discover/mychannel/org7-example.com/tlscert \
 --peerAddresses192.168.69.107:7051
 --tlsRootCertFiles /vars/discover/mychannel/org8-example.com/tlscert \
 --peerAddresses192.168.69.108:7051
 --tlsRootCertFiles /vars/discover/mychannel/org9-example.com/tlscert \
 --peerAddresses 192.168.69.109:7051
 --tlsRootCertFiles /vars/discover/mychannel/org10-example.com/tlscert \

```

**Comment by litong01** [comment]
which peer of an org to use in commit is not relevant. As long as there is one from an org, then it is fine. The code you have is correct. But you can do the commit one org after the other. If your server 1 has 4 orgs, the commit will use one from each org. I am not really sure where you are going with this.

**Comment by pkirkinezis** [comment]
> 
> 
> which peer of an org to use in commit is not relevant. As long as there is one from an org, then it is fine. The code you have is correct. But you can do the commit one org after the other. If your server 1 has 4 orgs, the commit will use one from each org. I am not really sure where you are going with this.

@litong01 
For example generic example
You have 10 servers . Each one of this 10 servers has one organization.
Server 1 : Org1 with 2 peers 
Server 2 : Org2 with 2 peers 
Server 3 : Org3 with 2 peers 
Server 4 : Org4 with 2 peers 
Server 5 : Org5 with 2 peers 
Server 6 : Org6 with 2 peers 
Server 7 : Org7 with 2 peers 
Server 8 : Org8 with 2 peers 
Server 9 : Org9 with 2 peers 
Server 10 : Org10 with 2 peers .

You have created a channel mychannel that includes ORG1-ORG2-ORG3-ORG4-ORG5-ORG6-ORG7-ORG8-ORG9-ORG10.

Lest say you want to install "simple" chaincode on this channel to all organization(1-10) what will you do ? 
Is there any other way than the one I described earlier in my commit command ?

**Comment by litong01** [comment]
@pkirkinezis if your policy is default (majority), then if you are using minifabric, I think you can import all the orgs nodes into one node, this should make all node available to that server, then do a commit which will commit to all orgs. if you do not import all the org nodes, then I believe you have to import enough number of orgs into one server, so that you can do commit with enough number of orgs. At this point, I am not really sure what happens with the other 4 orgs. you can probably do a test case like this:

```
1. 10 orgs network, install chaincode onto all peers in all orgs
2. each org approveformyorg
3. import 5 org nodes to one org
4. do commit which should succeed since you have total of 6 orgs committing
5. try to do a commit on one of the other 4 orgs and see what happens.
```
Let me know how it goes.

BTW, I've recently added capabilities of having multiple networks on one server. For example, you can create 3 working directories on one server, each working directory can have its own spec.yaml file, if you go into each working directory and do `minifab netup` (you have to use unique peer name and orderer names to avoid name clashes), you should have multiple sites, this is to mimic multiple servers using just one server.

**Comment by pkirkinezis** [comment]
> @pkirkinezis if your policy is default (majority), then if you are using minifabric, I think you can import all the orgs nodes into one node, this should make all node available to that server, then do a commit which will commit to all orgs. if you do not import all the org nodes, then I believe you have to import enough number of orgs into one server, so that you can do commit with enough number of orgs. At this point, I am not really sure what happens with the other 4 orgs. you can probably do a test case like this:
> 
> ```
> 1. 10 orgs network, install chaincode onto all peers in all orgs
> 2. each org approveformyorg
> 3. import 5 org nodes to one org
> 4. do commit which should succeed since you have total of 6 orgs committing
> 5. try to do a commit on one of the other 4 orgs and see what happens.
> ```
> 
> Let me know how it goes.
> 
> BTW, I've recently added capabilities of having multiple networks on one server. For example, you can create 3 working directories on one server, each working directory can have its own spec.yaml file, if you go into each working directory and do `minifab netup` (you have to use unique peer name and orderer names to avoid name clashes), you should have multiple sites, this is to mimic multiple servers using just one server.

Yeah i saw that is very interesting . 
As for exchanging I will try to do that. 
BUT what i described earlier is working 100% and i dont have to exchange anything only proceed with a `minifab discover ` for the specific channel and then add all the discovered orgs into the commit command manually

**Comment by pkirkinezis** [comment]
@litong01 how i make the copied organizations to be seen by minifab .
I imported them by copping the keyfile. Is there any specific way to import other organizations ?

**Comment by litong01** [comment]
@pkirkinezis please close this one since it is not an issue for minifabric.

**Comment by litong01** [comment]
no activities over two weeks. closing.
