### ISSUE TITLE
Error on chaincode install

### ISSUE THREAD

**Issue by makkasu** [litong01/minifabric#42]
First off, I was at the HLF developer call and was seriously impressed with this project so thanks for your hard work.

I've just ran into an error when trying to use minifab on my work laptop (Windows 10 Enterprise Version 1809, build 17763.1282; Docker desktop: version 19.03.8, build afacb8b):

After installing minifab using `curl -o minifab.cmd -sL https://raw.githubusercontent.com/litong01/minifabric/master/minifabwin` (the short url didn't work), I ran `minifab up`. It pulled some images, span up the network but then failed on chaincode install:

```
.................................                                                                                                  
# Running operation: ******************************************
 cc install                                                                                                                       
.......                                                                                                                            
# Run the chaincode install script on cli container ***********                                                                      
non-zero return code                                                                                                               
go: github.com/golang/protobuf@v1.3.1: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.3.1.mod": x509: certificate signed by unknown authority                                                                                                         
Error: failed to normalize chaincode path: 'go list' failed with: go: github.com/golang/protobuf@v1.3.1: Get "https://proxy.golang.org/github.com/golang/protobuf/@v/v1.3.1.mod": x509: certificate signed by unknown authority: exit status 1  Error: failed to read chaincode package at 'simple_go_1.0.tar.gz': open simple_go_1.0.tar.gz: no such file or directory  
# STATS *******************************************************                                                                    
minifab: ok=206 failed=1   
```

Not sure if this is a bug or an issue with my procedure. Any ideas? 
Attached is the full output from `minifab up`.
[minifab_out.txt](https://github.com/litong01/minifabric/files/4982029/minifab_out.txt)

**Comment by makkasu** [comment]
A bit of further information: I'm not able to install chaincode written in any language. The error messages are different, but in all cases they fail at `cc install`.

**Comment by litong01** [comment]
@makkasu The fact that you can not even access the tinyurl made me think that your network may have some restrictions. It is typical that during the chaincode install, the fabric network will need to access golang dependency repo to pull necessary libararies. without being able to do that, it is a bit difficult to build up the chaincode package. what version of fabric are you using? can you try from a linux machine?

**Comment by makkasu** [comment]
Thanks for the fast response - my network is restricted yes, so that's probably the problem. To get around these restrictions I have been using a cloud based ubuntu VM, where I have hyperledger working fine so I assume minifab would work too. Do you have any recommendations about how to gather the dependencies that need to be whitelisted?

**Comment by litong01** [comment]
if you use golang, then google site can not be blocked. other languages, I am not really sure.

**Comment by makkasu** [comment]
Ok, I'll dig into it. Thanks for the help
