### ISSUE TITLE
Source code and compile script/Instruction for minifabric

### ISSUE THREAD

**Issue by gosyseng** [litong01/minifabric#44]
Hi,

I am exploring this minifabric project. looks great but where is the full source code for minifabric and how do I compile it ? I appreciate some instructions here.  Thanks !

**Comment by davidkhala** [comment]
Here is the full source code. 
But indeed, we need a local build document
Some hints I could provide:
https://github.com/litong01/minifabric/blob/master/minifab : entrance for Unix-like system 
https://github.com/litong01/minifabric/blob/master/minifabwin: entrance for Windows

**Comment by litong01** [comment]
@gosyseng To build the minifabric docker image from source is very easy. run this command in the root directory of minifabric

```
docker build -t hfrd/minifabric:latest .
```

**Comment by litong01** [comment]
Doc has been updated to reflect the build command.
