### ISSUE TITLE
Getting "x509: certificate is valid for tlsca.org1.example.com, not ca.org1.example.com" errors

### ISSUE THREAD

**Issue by ChrisSargent** [litong01/minifabric#5]
# Issue:

Getting "x509: certificate is valid for tlsca.org1.example.com, not ca.org1.example.com" errors

# Problem

This file https://github.com/litong01/minifabric/blob/master/playbooks/nodes/templates/caenv.j2, is the .env file for the `ca.org1.example.com` server.

However, `FABRIC_CA_SERVER_TLS_CERTFILE` is set to the cryptogen tlsca cert from `vars/keyfiles/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem`, which, as can be seen below, is signed only for use on the `tlsca.org1.example.com` server.

Therefore all calls to `ca.org1.example.com` (which is our only ca url available) fail because of the above error.

# Fix

The code should use the `vars/keyfiles/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem` file

Further confirmation comes from looking at the configuration in the fabric samples repo, we can see that this is actually done in the same way there too: https://github.com/hyperledger/fabric-samples/search?q=FABRIC_CA_SERVER_TLS_CERTFILE&unscoped_q=FABRIC_CA_SERVER_TLS_CERTFILE

See Pull Request: #6 

# Certificates

## vars/keyfiles/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem

```
Common Name: ca.org1.example.com
Issued By: org1.example.com
Issuing Certificate: ca.org1.example.com
Serial Number: 800CFF1D63477C1F848284837E4E77B9
Signature: ecdsa-with-SHA256
Valid From: 18:46:00 17 Feb 2020
Valid To: 18:46:00 14 Feb 2030
Key Usage: Digital Signature, Key Encipherment, Certificate Sign, CRL Sign
Extended Key Usage: TLS Web Client Authentication, TLS Web Server Authentication
Basic Constraints: CA:TRUE
Subject Key Identifier: 54:31:5B:03:75:69:8E:DC:C7:FE:F3:CA:D2:34:7F:5F:DA:BF:5F:1A:65:84:6A:82:3C:78:B5:DB:95:FD:49:F8
```

## vars/keyfiles/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

```
Common Name: tlsca.org1.example.com
Issued By: org1.example.com
Issuing Certificate: tlsca.org1.example.com
Serial Number: 567998BD56C9D37328CF6FA6806D5F17
Signature: ecdsa-with-SHA256
Valid From: 18:46:00 17 Feb 2020
Valid To: 18:46:00 14 Feb 2030
Key Usage: Digital Signature, Key Encipherment, Certificate Sign, CRL Sign
Extended Key Usage: TLS Web Client Authentication, TLS Web Server Authentication
Basic Constraints: CA:TRUE
Subject Key Identifier: 6B:32:8F:6A:11:0A:74:57:12:44:D7:9E:75:23:CD:46:82:C7:C9:C0:80:1A:98:6B:1D:71:88:DF:34:D3:04:04
```

## FABRIC_CA_SERVER_CA_CERTFILE=/certs/ca/ca.org1.example.com-cert.pem

```
Common Name: ca.org1.example.com
Issued By: org1.example.com
Issuing Certificate: ca.org1.example.com
Serial Number: 800CFF1D63477C1F848284837E4E77B9
Signature: ecdsa-with-SHA256
Valid From: 18:46:00 17 Feb 2020
Valid To: 18:46:00 14 Feb 2030
Key Usage: Digital Signature, Key Encipherment, Certificate Sign, CRL Sign
Extended Key Usage: TLS Web Client Authentication, TLS Web Server Authentication
Basic Constraints: CA:TRUE
Subject Key Identifier: 54:31:5B:03:75:69:8E:DC:C7:FE:F3:CA:D2:34:7F:5F:DA:BF:5F:1A:65:84:6A:82:3C:78:B5:DB:95:FD:49:F8
```

## FABRIC_CA_SERVER_TLS_CERTFILE=FABRIC_CA_SERVER_TLS_CERTFILE

```
Common Name: tlsca.org1.example.com
Issued By: org1.example.com
Issuing Certificate: tlsca.org1.example.com
Serial Number: 567998BD56C9D37328CF6FA6806D5F17
Signature: ecdsa-with-SHA256
Valid From: 18:46:00 17 Feb 2020
Valid To: 18:46:00 14 Feb 2030
Key Usage: Digital Signature, Key Encipherment, Certificate Sign, CRL Sign
Extended Key Usage: TLS Web Client Authentication, TLS Web Server Authentication
Basic Constraints: CA:TRUE
Subject Key Identifier: 6B:32:8F:6A:11:0A:74:57:12:44:D7:9E:75:23:CD:46:82:C7:C9:C0:80:1A:98:6B:1D:71:88:DF:34:D3:04:04
```

**Comment by litong01** [comment]
@ChrisSargent I looked into this and just found that the issue is actually because the certificates created for ca and tlsca using hardcode names (no surprising). For example, for org0.example.com, ca certificate was created using CN=ca.org0.example.com. For tls certificate, the CN=tlsca.org0.example.com. So  I think that the issue is not the certificates wrong, it is really the container name or hostname issue. if you change your spec like this, things will work.

fabric:
  cas:
  - "tlsca.org0.example.com"
  - "tlsca.org1.example.com"
  peers:
  - "peer1.org0.example.com"
  - "peer2.org0.example.com"
  - "peer1.org1.example.com"
  - "peer2.org1.example.com"
  orderers:
  - "orderer1.example.com"
  - "orderer2.example.com"
  - "orderer3.example.com"

@ChrisSargent can you try that?

**Comment by litong01** [comment]
I understand why cryptogen did that. but it is really not very nice. If to make it really really working, then we need to provide a lot of information for CA node such as domain, SANs etc. Let me think about that. For now, you can get by this issue by using the ca node name like I had above.
