### ISSUE TITLE
Using custom spec.yaml causes Create Channel FORBIDDEN -- implicit policy evaluation failed error

### ISSUE THREAD

**Issue by opentaps** [litong01/minifabric#52]
Hello, 

I'm getting started with minifabric, and I tried to set up my own spec.yaml  It's able to bring up the docker containers, but then runs into the error
# Run the channel creation script on cli container ************
  non-zero return code
  2020-08-12 17:44:55.962 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
  2020-08-12 17:44:55.996 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /vars/configtx.yaml
  2020-08-12 17:44:55.996 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 003 Generating new channel configtx
  2020-08-12 17:44:56.119 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 004 Writing new channel tx
  2020-08-12 17:44:56.232 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
  Error: got unexpected status: FORBIDDEN -- implicit policy evaluation failed - 0 sub-policies were satisfied, but this policy requires 1 of the 'Writers' sub-policies to be satisfied: permission denied

I haven't changed anything except use the attached spec.yaml  

Attached is also the log file.  

Thanks!
[minifab-specyaml-channel-error.zip](https://github.com/litong01/minifabric/files/5064739/minifab-specyaml-channel-error.zip)

**Comment by litong01** [comment]
@opentaps The issue is that you have a peer org and orderer org using same name. this is actually a problem. Please use different org for peer and orderer.

**Comment by opentaps** [comment]
@litong01 Thanks for getting back to me.  Yes, changing the orderers to order1.example.com and order1.example.org got it to work.

Is this intentional?  I saw in https://hyperledger-fabric.readthedocs.io/en/release-1.4/Fabric-FAQ.html#ordering-service - 
"Question: | Can I have an organization act both in an ordering and application role?

Answer: Although this is possible, it is a highly discouraged configuration.  ..."

**Comment by litong01** [comment]
yes. that is right. You can not do it in minifabric. In minifabric, ordering org and peer org must all unique. If your issue is resolved, please close this.

**Comment by opentaps** [comment]
OK, great.  Thank you!
