### ISSUE TITLE
Errors installing chaincode

### ISSUE THREAD

**Issue by opentaps** [litong01/minifabric#53]
I'm going through the [Chaincode video](https://www.youtube.com/watch?v=r108lkV7auk&list=PL0MZ85B_96CExhq0YdHLPS5cmSBvSmwyO&index=3) again.  There's no mycc in the directory, but there is a simple which looks similar.  

I've removed my spec.yaml and gone back to the default set up.

However, trying to
./minifab install -n simple
gives error
  non-zero return code
  Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': chaincode already successfully installed

Then trying mycc 
./minifab install -n mycc

  non-zero return code
  /vars/run/ccinstall.peer1.org0.example.com.sh: line 9: cd: /go/src/github.com/chaincode/mycc: No such file or directory
  /vars/run/ccinstall.peer1.org0.example.com.sh: line 13: cd: go: No such file or directory
  go: cannot find main module; see 'go help modules'
  /vars/run/ccinstall.peer1.org0.example.com.sh: line 16: cd: OLDPWD not set
  Error: error getting chaincode bytes: 'go list' failed with: can't load package: package github.com/chaincode/mycc/go: cannot find package "github.com/chaincode/mycc/go" in any of:
  	/usr/local/go/src/github.com/chaincode/mycc/go (from $GOROOT)
  	/go/src/github.com/chaincode/mycc/go (from $GOPATH): exit status 1
  Error: failed to read chaincode package at 'mycc_go_1.0.tar.gz': open mycc_go_1.0.tar.gz: no such file or directory

I've attached the log.

Thank you!
[minifab-chaincode-errors.log](https://github.com/litong01/minifabric/files/5065495/minifab-chaincode-errors.log)

**Comment by litong01** [comment]
@opentaps these are all user errors. when you do `minifab up` it already does many things already including installing chaincode named `simple` which comes with minifabric. if you want to install a chaincode named mycc you will have to make it available. Please read the docs before you open issues.

**Comment by opentaps** [comment]
Sorry!

**Comment by opentaps** [comment]
Sorry to bother you again, @litong01, but I'm following your [Chaincode Video at 8:00](https://www.youtube.com/watch?v=r108lkV7auk&list=PL0MZ85B_96CExhq0YdHLPS5cmSBvSmwyO&index=3&t=480s)

In this video you show installing mycc, but there is no mycc in the ./var/chaincode directory.  I think "simple" is what you mean based on the example in the video.

The problem is that when I run 
$ ./minifab invoke -p '"query", "a"'
I get error
  Error: endorsement failure during invoke. response: status:500 message:"make sure the chaincode simple has been successfully defined on channel coolchannel and try again: chaincode simple not found"

but when I run
$ ./minifab install -n simple
  Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': chaincode already successfully installed

Thank you.
[Uploading minifab-chaincode-install-invoke-errors.log…]()

**Comment by opentaps** [comment]
I cleaned up and started over, and now everything worked.  Thanks again.
