### ISSUE TITLE
Integrating Minifab Network with VS Code : A Problem with Wallets

### ISSUE THREAD

**Issue by edkaz** [litong01/minifabric#55]
Hello

I am following the Tutorial 5 in the video series and trying to connect my Minifab Network with VS Code. My problem is that the Wallet directory structure and contents generated by Minifab do not (seem to) match up with what VS Code IBM Blockchain Extension expects. 

Here is my generated directory tree:
```[bash]
vscode
├── vscodenodefile.json
└── wallets
    ├── Org_1.kasese.com
    │   └── Admin.id
    └── Order.kasese.com
        └── Admin.id
```
When I try to add a new wallet for, say Org_1 I get the following error:
```[bash]
Failed to add a new wallet: No identities found in wallet: [deleted] /vars/profiles/vscode/wallets/Org_1.kasese.com
```
Platform : MacOS 10.15.6
VS Code : 1.48.0
IBM Blockchain Extension : 1.0.36

Minifab sets up a network, joins the peers and installs chaincode okay. The network and vars directory are on my local machine. 

Have I missed something in generating the wallets. Help very much appreciated.

Regards - Ed.

**Comment by litong01** [comment]
@edkaz vscode fabric extension as of now does not support fabric 2.0 wallet. You have to use an older version like 1.4.5. When you have that version of fabric setup, the created wallet format will be connect, then you can import into vs code.

**Comment by edkaz** [comment]
@litong01 Okay thank you. I can do that but my chaincode is very much Fabric 2.0. So .. is there a workaround for fabric 2.0 wallets?

**Comment by yilin-sai** [comment]
Hi @edkaz , IBM blockchain vscode extension has v2.0.0 beta releases which support Fabric 2.0. The latest one is https://github.com/IBM-Blockchain/blockchain-vscode-extension/releases/tag/v2.0.0-beta.6. I think that can be the workaround, but I'm 100% sure

**Comment by edkaz** [comment]
@yilin-sai Thank you. I will give it a try a let you know how it goes.

**Comment by edkaz** [comment]
@yilin-sai Works perfectly! 
Thank you very much - Ed
