### ISSUE TITLE
Question: Do we need to call Init() on our Chaincode or is there a way to change the setting of `init-required`

### ISSUE THREAD

**Issue by edkaz** [litong01/minifabric#56]
Hello

A quick question regarding Init() functions on Chaincode. When using _Minifab_ do I always need to provide and call the ```Init()``` function or can I change the value of ```init-required```? 

Regards - Ed

**Comment by litong01** [comment]
@edkaz That is completely up to the chaincode developer and your business logic. init-required is for a chaincode deployer to specify exactly that. Please ask similar questions on the channel rather than opening an issue.
