### ISSUE TITLE
Question: Can we have some information on how to backup and restore ledger data? 

### ISSUE THREAD

**Issue by sivaramsk** [litong01/minifabric#57]
Can we have some information on how to backup and restore ledger data? The information on the official does are not that helpful. May be adding `minifab backup` would be very helpful for the minifab audience.

**Comment by litong01** [comment]
@sivaramsk blockchain at its heart is distributed and redundant, one node can replicate the ledger from other nodes even if they are not in the same organization, backup is practically not necessary. But if you really want to do that in minifabric, you probably can backup the docker volume each peer node has, that is how minifabric peers survive machine crashes and restart. Each node has a docker volume created for and you can easily find these volume and inspect what on them. Also, please do not open issues when you actually were asking questions. Take your question to the fabric-mini channel. I monitor that channel often.

**Comment by sivaramsk** [comment]
I apologize and thanks for the reply.
