### ISSUE TITLE
VSCode Extension Compatibility: creating new identity fails with Error ['ca.org0.example.com' does not exist]

### ISSUE THREAD

**Issue by yilin-sai** [litong01/minifabric#58]
## Description

I'm using minifabric with IBM Blockchain Platform VSCode extension. Everything works great so far except when I try to create a new identity by right clicking the ca node in the fabric environment, as shown below:

<img width="516" alt="Screen Shot 2020-08-18 at 11 14 41 am" src="https://user-images.githubusercontent.com/42603306/90459263-213ea200-e144-11ea-8931-7758928ae1d8.png">

The error message I got is
```
Issue creating new identity: fabric-ca request register failed with errors [[ { code: 19, message: "CA 'ca.org0.example.com' does not exist" } ]]
```

After some investigation I found that in minifabric the name of every CA is set to 'ca', but VSCode extension uses 'ca.org0.example.com' as ca name when connecting to minifabric, which leads to the error above.

Is there a way to align the minifabric ca names with the ones in VSCode extension?

## Environment

VSCode 1.48.0
IBM Blockchain Platform VSCode Extension v2.0.0-beta.6

**Comment by litong01** [comment]
I think that the issue is that your vscode may not be able to reach ca node. You can change your ca node name by customizing your fabric network spec file. You can probably also check how the VS code send requests to ca node.

**Comment by yilin-sai** [comment]
Thanks for the reply @litong01 ! I checked the log of the ca node docker container, it also has the same error:
```
2020/08/17 23:57:40 [INFO] Listening on https://0.0.0.0:7054

2020/08/18 00:05:39 [INFO] 192.168.32.1:39848 POST /api/v1/register 404 19 "CA 'ca.org0.example.com' does not exist"
```
so I believe ca node has been reached.

-----
Currently my spec.yaml file uses the following ca configs:
```
fabric:
  cas:
  - "ca.org0.example.com"
  - "ca.org1.example.com"
```
and the generated connection profile shows the ca name is 'ca':
```
......
"certificateAuthorities":
  "ca.org0.example.com":
    ......
    "caName": "ca"
    ......
  "ca.org1.example.com":
    ......
    "caName": "ca"
    ......
```

However, I just realised in the generated vscode profile, the ca_name is set to the node name rather than 'ca':
```
$ cat ./vars/profiles/vscode/vscodenodefile.json
[
  {
    ......
  {
    "name": "ca.org0.example.com",
    "ca_name": "ca.org0.example.com",
    ......
  },
  {
    "name": "ca.org1.example.com",
    "ca_name": "ca.org1.example.com",
    ......
  }
]
```
I think that's what caused the mismatch.

-----

I just manually modified the ca_name fields in `./vars/profiles/vscode/vscodenodefile.json` to 'ca', but then the ca docker container reports:
```
2020/08/18 02:19:17 [INFO] 192.168.32.1:40104 POST /api/v1/register 401 30 "Certificate not found with AKI 'c50a91b3093cd1f69bdd4fa783fc82dbb41ede967d59dc8059b2703be1612355' and serial '21dae95ffeb1f1b197eadbd4c91aefed'"
```
It seems some certificate also needs to be updated, but I don't have any idea what certificate is this.

**Comment by litong01** [comment]
@yilin-sai you probably can check if the minifabric generated ca cert matches the ca node name `ca.org0.example.com`, if it does, then it should be correct. If it does not, then there has to be an error in generating the cert. but I am very positive, that minifabric did it correctly. Also you can manually run the CA command that vscode was trying to do.

**Comment by yilin-sai** [comment]
Hi @litong01 ,

just figured out what's happening. The `certgen` operation uses `cryptogen` to generate all certificates (done in [this script](https://github.com/litong01/minifabric/blob/c072fbce1c366a83d4e133d3efbf0965209e0db7/playbooks/ops/certgen/templates/certtxgen.j2)). As a result, users' certificates in `vars/keyfiles/peerOrganizations/<org>/users/` are not issued by the CA. This explains why CA reports `Certificate not found` when receiving the user's cert.

Is there a plan to use CAs to issue user certificates in future minifabric releases so that identity management is supported?

**Comment by litong01** [comment]
@yilin-sai doing that will require all the certs being created using ca so that the ca has to be up running first, this certainly complicates things. I do not see how soon we can support that, but one way to do this is that you can create bunch of certs using a ca, then place these certs and keys under keyfiles directory, minifabric will use them to set things up. I would think a script to do wont be too difficult to do. Currently have no plans to add that function to minifabric.

**Comment by yilin-sai** [comment]
Cool. Personally I'd like to see some identity management functionality in minifabirc because I found lots of people encountering problems with fabric CAs, but totally understand that it would add complexity. Thank you very much for you answers!
