### ISSUE TITLE
 Produce the key var file

### ISSUE THREAD

**Issue by xiegangqingnian** [litong01/minifabric#60]
# Running operation: ******************************************
  start network
.......[WARNING]: Unable to convert data using to_nice_json, falling back to to_json:
'allkeys' is undefined

# Produce the key var file ************************************
  The task includes an option with an undefined variable. The error was: 'allkeys' is undefined
  
  The error appears to be in '/home/playbooks/common/processkeys.yaml': line 56, column 5, but may
  be elsewhere in the file depending on the exact syntax problem.
  
  The offending line appears to be:
  
  
    - name: Produce the key var file
      ^ here
  

# STATS *******************************************************
minifab: ok=54	failed=1	

谢谢~

**Comment by litong01** [comment]
@xiegangqingnian this is really strange. are you using the latest code? how to re-produce this error? Please describe the steps from the very beginning.

**Comment by litong01** [comment]
@xiegangqingnian if you are using the latest code, try to do the following command:
```minifab cleanup
minifab up``` to see if the issue persists.

**Comment by litong01** [comment]
@xiegangqingnian no response. closing this issue.

**Comment by edkaz** [comment]
Hello 
I have had the same error come up many times. The cause for me has always been that the ./vars directory not being completely empty; ```[bash] minifab cleanup``` always has so far always fixed this problem for me.
