### ISSUE TITLE
why "minifab up " can not  run ?

### ISSUE THREAD

**Issue by Wws-zonda** [litong01/minifabric#61]
`ZZ@A:~$ cd mywork/
Z@A:~/mywork$ ls
minifab  minifabric
Z@A:~/mywork$ minifab up
minifab：未找到命令
Z@A:~/mywork$ whereis minifab
minifab:
`

According to the README.md to build, but I don’t know why I can’t run the minifab script 
my system is：ubuntu18.04

**Comment by litong01** [comment]
@Wws-zonda if you did not move minifab file to a location where your $PATH includes, then you will have to do this
```./minifab up```, that is how linux works.

**Comment by litong01** [comment]
@Wws-zonda if you just build it using the build process, then the minifab script probably is still in the repo directory, you will need to copy that to a location as part of your $PATH. Again, basic linux way of doing things.

**Comment by Wws-zonda** [comment]
Well, I just noticed that this is also a necessary step. Thank you
