### ISSUE TITLE
Wrong version in nodeprofile json template

### ISSUE THREAD

**Issue by manjush08** [litong01/minifabric#70]
https://github.com/litong01/minifabric/blob/78d44facc6268cb9586d5cfdc7f5fd60ec088749/playbooks/ops/profilegen/templates/nodeprofile.j2#L4

The node profile version should be 1.0.0, since 1.1.0 is not supported as of now, and throws an error.

**Comment by litong01** [comment]
@manjush08 my understanding is that the field is not used. Can you confirm that? Will change that to 1.0.0 anyway, but please make sure if the field is being used.

**Comment by litong01** [comment]
@manjush08 both profiles in yaml and json format have been changed to 1.0.0
