### ISSUE TITLE
minifab not working on a ubuntu16 virtualbox

### ISSUE THREAD

**Issue by nachikettapas** [litong01/minifabric#74]
I tried to setup fabric network using minifab. I used a Ubuntu16 based osbox image and installed docker.

```
osboxes@osboxes:~/mywork$ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:59 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:30 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
osboxes@osboxes:~/mywork$ 
```
Then I used `minifab up` to start the network (without any spec.yaml file). The setup fails with the following error.
```
osboxes@osboxes:~/mywork$ minifab up -f minifab
Minifab Execution Context:
    FABRIC_RELEASE=2.2.0
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=addr:10.0.2.15
    WORKING_DIRECTORY: /home/osboxes/mywork
...
# Preparing for the following operations: *********************
  verify options, download images, generate certificates, start network, network status, channel create, channel join, anchor update, profile generation, cc install, cc approve, cc commit, cc initialize, discover
.......
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  download images
............
# Running operation: ******************************************
  generate certificates
..
# Running operation: ******************************************
  start network
......
# Create env file for all nodes *******************************
  All items completed
    
[WARNING]: Failure using method (v2_runner_on_failed) in callback plugin
(<ansible.plugins.callback.minifab.CallbackModule object at 0x7f84c32dc1f0>):
unsupported operand type(s) for +: 'dict_keys' and 'dict_keys'

# STATS *******************************************************
minifab: ok=53	failed=1	

real	0m16.691s
user	0m12.781s
sys	0m1.766s
```

**Comment by nachikettapas** [comment]
When I run the command with -f dense option, I see that the script fails at task 85.

**Comment by mariusz-jachimowicz-83** [comment]
On my virtual machine with Ubuntu 16 it also doesn't work, but for different reason.
I see that this:

```
- name: "Create ca private key and tls key"
  command: >-
    openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -pkeyopt ec_param_enc:named_curve -out {{ orgrootpath }}/{{ item }}
    openssl genpkey -algorithm ed25519 -aes256 -out {{ orgrootpath }}/{{ item }}
  with_items:
  - "ca/priv_sk"
  - "tlsca/priv_sk"
```
creates empty files. I haven't found yet why.

**Comment by litong01** [comment]
@mariusz-jachimowicz-83 @nachikettapas were you all using the latest image? can you do this command to make sure?
```
docker pull hfrd/minifab:latest
```
This is rather strange problem since the command is running inside a container and should not produce such errors. I wonder if you have run ```minifab up``` multiple times without doing ```minifab cleanup```?

can you all try that?
you can not really run `minifab up` multiple times without `minifab cleanup` in between.

**Comment by litong01** [comment]
@mariusz-jachimowicz-83 @nachikettapas ubuntu 16.04 is at end of the life, and I do not really have an env to test it. Can you try it on ubuntu 18.04 or later and see if the same error occurs?

**Comment by litong01** [comment]
@mariusz-jachimowicz-83 @nachikettapas I tested on Ubuntu 16.04, I can confirm that the openssl certificate generation fails during to the IP address problem. I am not really sure why. At the moment, please use a newer Ubuntu like 20.04.

**Comment by litong01** [comment]
@mariusz-jachimowicz-83 @nachikettapas OK, I think I know what the issue is. a quick fix is coming up.

**Comment by litong01** [comment]
@mariusz-jachimowicz-83 @nachikettapas The problem is now fixed, the fix is in minifab script, you should only need to download the latest minifab script to enjoy the latest version by doing this
```
curl -o minifab -sL https://tinyurl.com/twrt8zv
```
replace your existing minifab with the downloaded one, then you should be good to go.

**Comment by nachikettapas** [comment]
I tried the new script and I was able to setup a basic fabric network. Closing the issue. Thank you for a quick turnaround.
