### ISSUE TITLE
"Iteration Over Null" Issue with "Minifab Commit" Command

### ISSUE THREAD

**Issue by davidmacfadyen** [litong01/minifabric#75]
Hi Tong, 
When going through your Minifabric videos, I see that the third film on Chaincode explains the following procedure, which unfortunately fails as a new chaincode commit script (in this case from SampleCC) is run on cli containers. 
Here's the context. The problem is in the final lines.
Any ideas?
Thanks
David 

====

```
C:\Users\Loaner\mywork
λ minifab install -n samplecc -l go
Minifab Execution Context:
    FABRIC_RELEASE=2.2.0
    CHANNEL_NAME=garagechannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=samplecc
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=192.168.1.6,172.17.222.33,255.255.255.240
    WORKING_DIRECTORY: /host_mnt/c/Users/Loaner/mywork
...
# Preparing for the following operations: *********************
  verify options, cc install
.......
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  cc install
...........................

# STATS *******************************************************
minifab: ok=45  failed=0

real    6m43.174s
user    1m26.832s
sys     0m16.468s

C:\Users\Loaner\mywork
λ minifab approve
Minifab Execution Context:
    FABRIC_RELEASE=2.2.0
    CHANNEL_NAME=garagechannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=samplecc
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=192.168.1.6,172.17.222.33,255.255.255.240
    WORKING_DIRECTORY: /host_mnt/c/Users/Loaner/mywork
...
# Preparing for the following operations: *********************
  verify options, cc approve
.......
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  cc approve
......

# STATS *******************************************************
minifab: ok=21  failed=0

real    1m3.370s
user    0m23.101s
sys     0m4.811s

C:\Users\Loaner\mywork
λ minifab commit
Minifab Execution Context:
    FABRIC_RELEASE=2.2.0
    CHANNEL_NAME=garagechannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=samplecc
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=192.168.1.6,172.17.222.33,255.255.255.240
    WORKING_DIRECTORY: /host_mnt/c/Users/Loaner/mywork
...
# Preparing for the following operations: *********************
  verify options, cc commit
.......
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  cc commit
............
# Run the chaincode commit script on cli container ************
  **non-zero return code
  jq: error (at <stdin>:1): Cannot iterate over null (null)
  Error: timed out waiting for txid on all peers**

# STATS *******************************************************
minifab: ok=27  failed=1

real    0m47.134s
user    0m19.760s
sys     0m4.444s 
```

**Comment by litong01** [comment]
Hmmm, I wonder if you have run minifab up more than once before running minifab cleanup. Can you try this process after you do minifab cleanup? There seems to be some residuals exist. Thx

**Comment by litong01** [comment]
I also wonder if your chaincode uses same initial parameter as simple chaincode?

**Comment by davidmacfadyen** [comment]
If I run `cleanup `several times to catch residuals, and then use the default `simple cc`, then we have this more positive result. I think I (also) wrongly assumed that **all** of the enclosed cc packages in had the same parameters and could be immediately deployed. 

`
//no cc to install in this example, since `simple `is the default setting and already included


`
C:\Users\Loaner\mywork
λ minifab approve
Minifab Execution Context:
    FABRIC_RELEASE=2.2.0
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=192.168.1.6,172.17.222.33,255.255.255.240    WORKING_DIRECTORY: /host_mnt/c/Users/Loaner/mywork
...
# Preparing for the following operations: *********************
  verify options, cc approve
.......
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  cc approve
......

# STATS *******************************************************
minifab: ok=21  failed=0

real    0m20.169s
user    0m12.705s
sys     0m2.673s

C:\Users\Loaner\mywork
λ minifab commit
Minifab Execution Context:
    FABRIC_RELEASE=2.2.0
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=192.168.1.6,172.17.222.33,255.255.255.240    WORKING_DIRECTORY: /host_mnt/c/Users/Loaner/mywork
...
# Preparing for the following operations: *********************
  verify options, cc commit
.......
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  cc commit
..............

# STATS *******************************************************
minifab: ok=29  failed=0

real    0m18.576s
user    0m13.046s
sys     0m2.598s
`
`

**Comment by poweruserincary** [comment]
@davidmacfadyen I noticed that you have used channel named mychannel and garagechannel, if you meant to use a channel garagechannel, then you need to specifically join peers to the channel, if you used `minifab up` command, then all the peers automatically joined default channel named mychannel. If you later create a channel named garagechannel, then join is necessary before approve and commit operation. Please try these commands in the following sequence:
```
minifab create -c garagechannel
minifab join
minifab install,approve,commit -n samplecc
```
or simply do this
```
minifab create,join,install,approve,commit -c garagechannel -n samplecc -l go
```
Once you got everything working, please close this issue.

**Comment by davidmacfadyen** [comment]
Yes absolutely, these commands work after `minfab up` has been run. 

So in enterprise settings, is your assumption that access to a new network is _always_ through `minifab up`, creating either an excess, unrequired channel--or that after using `minifab up`, `mychannel `can then be renamed--with new parameters--and therefore included in any network design?

**Comment by litong01** [comment]
@davidmacfadyen no, to expand an existing network (for example, setting up by using minifab up or any other way), you would do `minifab netup` which only stands up nodes such as peers, then you join the new peers or orgs into the existing network. I am not really sure I understand your statement above about unrequired or renamed, can you explain a bit more?

**Comment by davidmacfadyen** [comment]
Oh I hadn’t noticed the `netup` command in the videos, though I could very easily be mistaken! I just wondered how to initiate a network _without_ `mychannel`, which is automatically created by `Minifab up`

**Comment by litong01** [comment]
hmmm. use -c flag to change to name, please look at all the flags and command available in minifabric by simply run this
`minifab` command, also read this doc might help https://github.com/litong01/minifabric/blob/master/docs/README.md

**Comment by davidmacfadyen** [comment]
Perfect, thanks
