### ISSUE TITLE
Explorer not working.

### ISSUE THREAD

**Issue by Akayeshmantha** [litong01/minifabric#89]
Hi All 

After setting up mini fabric locally on my machine (ubuntu 18.04 LTS). I tried to start explorer. The starting process goes smoothly and the DB is up and healthy as well. But the main explorer container exits with the below error log.

```
Error: Cannot find module '/opt/explorer/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Any idea why this is happening. I started mini fabric with fabric 2.0.0.

Thanks a lot for the help.

**Comment by Akayeshmantha** [comment]
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by Akayeshmantha** [comment]
fixed by using tag 1.1.2 of hyper ledger explorer please note the latest was not working.

**Comment by litong01** [comment]
@Akayeshmantha so they changed the latest container image. and things are broke. Can you do a PR to specify the explorer container tag instead of using the latest?

**Comment by litong01** [comment]
@Akayeshmantha I've made the change to use the 1.1.2 explorer image for both db and explorer.

**Comment by Akayeshmantha** [comment]
@litong01 thanks a lot yes it works fine with tag 1.1.2

**Comment by chebyte** [comment]
@Akayeshmantha how do you change the tag for explorer? I have the same problem

**Comment by litong01** [comment]
hmmm. minifabric hardcode the explorer tag in its code. I believe it is using 1.1.2 currently.
