### ISSUE TITLE
dashboard up not working 

### ISSUE THREAD

**Issue by knagware9** [litong01/minifabric#9]
Could not find or access '/home/playbooks/ops/dashup/apply.yaml' on the Ansible Controller.

Thanks
Kamlesh

**Comment by knagware9** [comment]
also minifab container destroyed when I run dashboard up command

**Comment by litong01** [comment]
dashboard was removed in the latest release since it wont work for Fabric 2.0 or newer. I am working on renewing it.

**Comment by litong01** [comment]
are you looking for a specific function?

**Comment by knagware9** [comment]
Add/remove organization via dashboard.

**Comment by litong01** [comment]
@knagware9 The dashboard was originally done to support that but it wont work for 2.0, so I have removed it, to do that in 2.0, you will need to use the channel configuration process. I have detailed the process in one of the videos on how to use minifabric, the videos will be published soon on youtube.

**Comment by litong01** [comment]
I will update the readme document to reflect that as well.

**Comment by litong01** [comment]
@knagware9 The user guideline has been updated. The process to add a new organization to a channel is now described here https://github.com/litong01/minifabric/blob/master/docs/README.md#to-add-a-new-organization-to-your-fabric-network, you can follow the process there to add a new org.

**Comment by knagware9** [comment]
Thanks @litong01  I will go through it.

**Comment by litong01** [comment]
use removed function. the function again will be considered in the future.
