### ISSUE TITLE
Error while creating env file: AnsibleUndefinedVariable: 'dict object' has no attribute 'org0.example.com

### ISSUE THREAD

**Issue by SaidShah** [litong01/minifabric#91]
I am running on a Linux Ubuntu 20.04 with docker version 19.03.13
I installed minifab with: mkdir -p ~/Projects/mywork && cd ~/Projects/mywork && curl -o minifab -sL https://tinyurl.com/twrt8zv && chmod +x minifab

I have added the mywork directory to my path

I ran
./minifab down
./minifab cleanup
to remove any old docker images
ran
./minifab up
in the 
Create env file for all nodes step I received an error stating 
"AnsibleUndefinedVariable: 'dict object' has no attribute 'org0.example.com'" 
"AnsibleUndefinedVariable: 'dict object' has no attribute 'org1.example.com'"

I have included an image below
![image](https://user-images.githubusercontent.com/19719299/95373215-ae7fb680-08aa-11eb-8d2a-5d44c88883a2.png)

**Comment by litong01** [comment]
@SaidShah did you use your own spec.yaml file? if that is the case, you need to use `-o your.own.org` to start up.

**Comment by SaidShah** [comment]
The problem was resolved after I ran `sudo apt install net-tools`, so the issue was I did not have net-tools installed. 🤦 . Thank you for the quick reply.
